defaults:
  - preprocessor: tree
  - _self_

classifier:
  _target_: catboost.CatBoostClassifier
  n_estimators: 100
  learning_rate: 0.03
  depth: 4
  l2_leaf_reg: 3
  rsm: 0.8
  random_state: 42
  verbose: False
