_target_: imblearn.pipeline.Pipeline
steps:
  - - column_dropper
    - _target_: covid.feature.ColumnDropper
      columns_to_drop:
        - id

  - - missing_rate_dropper
    - _target_: covid.feature.HighMissingRateDropper
      missing_threshold: 0.05

  - - imputer
    - _target_: sklearn.impute.SimpleImputer
      strategy: most_frequent

  - - selector
    - _target_: sklearn.feature_selection.SelectKBest
      score_func:
        _target_: sklearn.feature_selection.chi2
        _partial_: true

  - - sampler
    - _target_: imblearn.over_sampling.RandomOverSampler
      random_state: 42

  - - scaler
    - _target_: sklearn.preprocessing.StandardScaler

  - - classifier
    - _target_: sklearn.svm.SVC
      random_state: 42